apiVersion: v1
kind: Secret

metadata: 
  name: easyshop-secrets
  namespace: easyshop

type: Opaque
stringData: 
  JWT_SECRET: "627b99263e1d2c9549832ae8e70bc577dc893e4c6089e16cdcb335905b822d56" 
  NEXTAUTH_SECRET: "pzGuDRJWttmduFmFoVAaBUdC1Qamvj7nBtXJ3oGQ9xM="  
    
